language: generic

#linux globals
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        - WX_CONFIG=debug
        - CONFIG=debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        - WX_CONFIG=release
        - CONFIG=intermediate
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        - WX_CONFIG=release
        - CONFIG=profile
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
        - WX_CONFIG=release
        - CONFIG=release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - os: linux
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
        - WX_CONFIG=debug
        - CONFIG=debug
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
    - os: linux
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
        - WX_CONFIG=release
        - CONFIG=intermediate
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
    - os: linux
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
        - WX_CONFIG=release
        - CONFIG=profile
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
    - os: linux
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
        - WX_CONFIG=release
        - CONFIG=release
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
#    - os: osx
#      compiler: clang
#      env:
#        - WX_CONFIG=debug
#        - CONFIG=debug
#    - os: osx
#      compiler: clang
#      env:
#        - WX_CONFIG=release
#        - CONFIG=intermediate
#    - os: osx
#      compiler: clang
#      env:
#        - WX_CONFIG=release
#        - CONFIG=profile
#    - os: osx
#      compiler: clang
#      env:
#        - WX_CONFIG=release
#        - CONFIG=release

git:
  submodules: false

before_install:
- git submodule update --init --recursive
- ./.travis.before_install.$TRAVIS_OS_NAME.sh

script:
- cd Dependencies
- ../premake.sh --wx-config=${WX_CONFIG} gmake
- make -j4 config=${CONFIG}_x64
- cd ..
- ./premake.sh gmake
- make -j4 config=${CONFIG}_x64

notifications:
  slack:
    rooms:
      secure: nn6rH9yj4/eJYNkAXrMIk4oVrweT3rznA5ATtuHzFeeG5uMT0qr1c1yQqDsSKsxtPan1RFo2awJ/PZkGQmuRVTcmVuaHs0eLPVrTXgfy2yjjuqwg4aLlK7PBEnv6oxUDyJOo9K9RYMcPIqXu0vcikgo+C4Oc6qL5MiOa7RleVjI=
    on_start: never
    on_success: always
    on_failure: always
